// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// SPDX-License-Identifier: MPL-2.0

use ahash::AHashSet;

use std::fs;
use std::io;
use std::path::Path;
use std::process::{Command, Stdio};

use std::fs::File;
use std::io::Write;
use std::path::PathBuf;
use std::process::Output;

use std::sync::Arc;
use tokio::sync::Semaphore;

use crate::database::database::Database;
use crate::execute::addformat::AddFormat;

const LANGUAGE_DAT: &[u8] = include_bytes!("../../assets/language.dat");
const LANGUAGE_DEF_BEGIN: &[u8] = include_bytes!("../../assets/language_begin.def");
const LANGUAGE_DEF_END: &[u8] = include_bytes!("../../assets/language_end.def");
const LANGUAGE_DAT_LUA: &[u8] = include_bytes!("../../assets/language.dat.lua");

const FMTUTIL_HEADER: &[u8] = include_bytes!("../../assets/fmtutil-hdr.cnf");

/// enviroment of commands
pub struct InstallContext<'a> {
    install_dir: &'a Path,
    texmf_bin_dir: &'a Path,
    texmf_dist: &'a Path,
    texmf_var: &'a Path,
    texmf_config: &'a Path,
    texmf_home: &'a Path,
}

impl<'a> InstallContext<'a> {
    pub fn setup(
        install_dir: &'a Path,
        texmf_bin_dir: &'a Path,
        texmf_dist: &'a Path,
        texmf_var: &'a Path,
        texmf_config: &'a Path,
        texmf_home: &'a Path,
    ) -> Self {
        InstallContext {
            install_dir,
            texmf_bin_dir,
            texmf_dist,
            texmf_var,
            texmf_config,
            texmf_home,
        }
    }

    // creazione dei file di sillabazione
    pub fn write_addhyphen(
        &self,
        dataset: &Database,
        pkg_list: &AHashSet<&str>,
    ) -> std::io::Result<()> {
        let dest = self.texmf_var.join("tex").join("generic").join("config");
        fs::create_dir_all(&dest)?;

        // language.dat
        let path_language_dat = dest.join("language.dat");
        let mut language_dat = File::create(&path_language_dat)?;
        language_dat.write_all(LANGUAGE_DAT)?;

        // language.def
        let path_language_def = dest.join("language.def");
        let mut language_def = File::create(&path_language_def)?;
        language_def.write_all(LANGUAGE_DEF_BEGIN)?;

        // language.dat.lua
        let path_language_dat_lua = dest.join("language.dat.lua");
        let mut language_dat_lua = File::create(&path_language_dat_lua)?;
        language_dat_lua.write_all(LANGUAGE_DAT_LUA)?;

        for hyphen in dataset.hyphen_directives_iter(pkg_list) {
            hyphen.write_language_dat(&mut language_dat)?;
            hyphen.write_language_def(&mut language_def)?;
            hyphen.write_language_dat_lua(&mut language_dat_lua)?;
        }

        language_dat.write_all(b"\n")?;
        language_def.write_all(LANGUAGE_DEF_END)?;
        language_dat_lua.write_all(b"}\n")?;

        language_dat.sync_all()?;
        language_def.sync_all()?;
        language_dat_lua.sync_all()?;

        // build ls-R index file for texmf-var
        // this file will be re-written later because generation of maps font
        // and formats write in this system directory but at the same time
        // they needs ls-R for searching during their execution
        let mut tree = crate::execute::tree::Node::default();
        tree.insert_file_path(&path_language_dat);
        tree.insert_file_path(&path_language_def);
        tree.insert_file_path(&path_language_dat_lua);

        let lsr_path = self.texmf_var.join("ls-R");
        let file = std::fs::File::create(&lsr_path)?;

        let mut writer = std::io::BufWriter::with_capacity(64 * 1024, file);
        tree.generate_texmf_dist_ls_r(&mut writer)?;

        Ok(())
    }

    /// write fmtutil.cnf
    pub fn write_addformat(
        &self,
        dataset: &'a Database,
        pkg_list: &AHashSet<&str>,
    ) -> std::io::Result<Vec<AddFormat<'a>>> {
        // get addformat directives
        let addformat_directives: Vec<AddFormat<'_>> =
            dataset.format_directives_iter(pkg_list).collect();

        // fmtutil_cnf location
        let dest = self.texmf_dist.join("web2c");
        fs::create_dir_all(&dest)?;

        let path_fmtutil_cnf = dest.join("fmtutil.cnf");
        let mut fmtutil_cnf = File::create(&path_fmtutil_cnf)?;

        fmtutil_cnf.write_all(b"# Generated by tlx (TeX Live eXpress)\n")?;
        fmtutil_cnf.write_all(FMTUTIL_HEADER.trim_ascii_end())?;

        for addformat_spec in &addformat_directives {
            let pkg_name = addformat_spec.pkg_name;
            writeln!(fmtutil_cnf, "#\n# from {pkg_name}:")?;
            addformat_spec.write_to(&mut fmtutil_cnf)?;
        }

        fmtutil_cnf.write_all(b"\n")?; // riga vuota finale
        fmtutil_cnf.sync_all()?;

        Ok(addformat_directives)
    }

    /// Configura ed esegue un comando TeX Live garantendo l'ambiente corretto.
    pub fn run_command(&self, program: &str, args: &[&str]) -> io::Result<()> {
        let program_path = self.texmf_bin_dir.join(program);

        // prepariamo la variabile PATH inserendo la cartella dei binari TeX Live in testa
        // let current_path = std::env::var_os("PATH").unwrap_or_default();
        // let new_path = std::env::join_paths(
        //    std::iter::once(self.bin_dir.to_path_buf()).chain(std::env::split_paths(&current_path)),
        // )
        // .map_err(|e| io::Error::new(io::ErrorKind::Other, e))?;

        println!("PATH child: {:?}", &self.texmf_bin_dir);

        let output = Command::new(&program_path)
            .env_clear()
            .args(args)
            .env("PATH", &self.texmf_bin_dir)
            .env("TEXMFROOT", &self.install_dir)
            .env("TEXMFDIST", &self.texmf_dist)
            .env("TEXMFSYSVAR", &self.texmf_var)
            .env("TEXMFSYSCONFIG", &self.texmf_config)
            .env("TEXMFHOME", &self.texmf_home)
            // variabili OS-level necessarie non legate a nessuna installazione TeX Live esistente
            .env(
                "WINDIR",
                std::env::var("WINDIR").unwrap_or_else(|_| r"C:\Windows".into()),
            )
            .env(
                "SystemRoot",
                std::env::var("SystemRoot").unwrap_or_else(|_| r"C:\Windows".into()),
            )
            .env("TEMP", std::env::var("TEMP").unwrap_or_default())
            .env("TMP", std::env::var("TMP").unwrap_or_default())
            .env(
                "USERPROFILE",
                std::env::var("USERPROFILE").unwrap_or_default(),
            )
            .env(
                "PATHEXT",
                std::env::var("PATHEXT").unwrap_or_else(|_| ".COM;.EXE;.BAT;.CMD".to_string()),
            )
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()?;

        if !output.status.success() {
            return Err(io::Error::new(
                io::ErrorKind::Other,
                format!(
                    "Il comando 'updmap-sys' è fallito con codice: {:?}\nstderr: {}\nstdout: {}",
                    output.status.code(),
                    String::from_utf8_lossy(&output.stderr),
                    String::from_utf8_lossy(&output.stdout),
                ),
            ));
        } else {
            println!(
                "stdout fmtutil-sys: {}",
                String::from_utf8_lossy(&output.stdout)
            );
            println!(
                "stderr fmtutil-sys: {}",
                String::from_utf8_lossy(&output.stderr)
            );
        }
        Ok(())
    }

    pub async fn build_all_formats(&self, formats: &Vec<AddFormat<'a>>) -> Vec<FormatResult> {
        let mut fmt_names: Vec<&'a str> = formats.iter().map(|fmt| fmt.name).collect();

        // ordinamento per raggruppare i duplicati vicini
        fmt_names.sort_unstable();

        // elimino tutti i duplicati
        fmt_names.dedup();

        // ordino dal peso più alto al più basso
        fmt_names.sort_by_key(|name| std::cmp::Reverse(format_weight_ii(name)));

        // il vincolo è il numero di core della CPU
        let cores = std::thread::available_parallelism()
            .map(|n| n.get())
            .unwrap_or(4); // fallback prudente se non rilevabile

        // -1 per lasciare margine al runtime tokio/thread principale di tlx
        let max_concurrent = cores.saturating_sub(1).max(1);
        println!("max_concurrent={max_concurrent}");

        let semaphore = Arc::new(Semaphore::new(max_concurrent));

        let mut handles = Vec::with_capacity(formats.len());

        for fmt in fmt_names {
            let fmt = fmt.to_string();
            let fmtutil_path = self.texmf_bin_dir.join("fmtutil-sys");

            let texmf_bin_dir = self.texmf_bin_dir.to_path_buf();
            let install_dir = self.install_dir.to_path_buf();
            let texmf_dist = self.texmf_dist.to_path_buf();
            let texmf_var = self.texmf_var.to_path_buf();
            let texmf_config = self.texmf_config.to_path_buf();

            let sem = semaphore.clone();
            let handle = tokio::spawn(async move {
                let _permit = sem.acquire_owned().await.expect("semaphore closed");
                build_single_format(
                    fmt,
                    fmtutil_path,
                    texmf_bin_dir,
                    install_dir,
                    texmf_dist,
                    texmf_var,
                    texmf_config,
                )
                .await
            });
            handles.push(handle);
        }

        let mut results = Vec::with_capacity(handles.len());
        for handle in handles {
            results.push(handle.await.expect("task panicked"));
        }
        results
    }
}

async fn build_single_format(
    fmt_name: String,
    fmtutil_path: PathBuf,
    texmf_bin_dir: PathBuf,
    install_dir: PathBuf,
    texmf_dist: PathBuf,
    texmf_var: PathBuf,
    texmf_config: PathBuf,
) -> FormatResult {
    let output = tokio::process::Command::new(fmtutil_path)
        .args(["--byfmt", &fmt_name])
        .arg("--nohash")
        .arg("--no-error-if-no-engine=luametatex,luajithbtex,luajittex,mfluajit")
        .arg("--no-strict")
        .env_clear()
        .env("PATH", texmf_bin_dir)
        .env("TEXMFROOT", install_dir)
        .env("TEXMFDIST", texmf_dist)
        .env("TEXMFSYSVAR", texmf_var)
        .env("TEXMFSYSCONFIG", texmf_config)
        // variabili OS-level necessarie non legate a nessuna installazione TeX Live esistente
        .env(
            "WINDIR",
            std::env::var("WINDIR").unwrap_or_else(|_| r"C:\Windows".into()),
        )
        .env(
            "USERPROFILE",
            std::env::var("USERPROFILE").unwrap_or_default(),
        )
        .output()
        .await; // niente spawn_blocking: il processo esterno è atteso in modo async

    match output {
        Ok(out) => FormatResult::from_output(fmt_name, out),
        Err(e) => FormatResult::io_error(fmt_name, e),
    }
}

#[derive(Debug)]
pub struct FormatResult {
    pub name: String,
    pub outcome: FormatOutcome,
}

#[derive(Debug)]
pub enum FormatOutcome {
    Success {
        stdout: String,
        stderr: String,
    },
    NonZeroExit {
        code: Option<i32>,
        stdout: String,
        stderr: String,
    },
    IoError(String), // messaggio dell'io::Error originale
}

impl FormatResult {
    pub fn from_output(name: String, out: Output) -> Self {
        let stdout = String::from_utf8_lossy(&out.stdout).into_owned();
        let stderr = String::from_utf8_lossy(&out.stderr).into_owned();
        let outcome = if out.status.success() {
            FormatOutcome::Success { stdout, stderr }
        } else {
            FormatOutcome::NonZeroExit {
                code: out.status.code(),
                stdout,
                stderr,
            }
        };
        FormatResult { name, outcome }
    }

    pub fn io_error(name: String, e: std::io::Error) -> Self {
        FormatResult {
            name,
            outcome: FormatOutcome::IoError(e.to_string()),
        }
    }

    pub fn is_success(&self) -> bool {
        matches!(self.outcome, FormatOutcome::Success { .. })
    }
}

/// Peso in "unità di calcolo" per la generazione di un formato, calibrato
/// da benchmark empirico (fmtutil-sys --byfmt, mediana di 3 run, overhead
/// di avvio ~7.5s già sottratto). Un'unità ≈ 1 secondo di build reale
/// oltre l'overhead fisso di processo.
fn format_weight(name: &str) -> u8 {
    match name {
        "uplatex" => 21,
        "platex-dev" => 20,
        "jadetex" | "pdfjadetex" => 18,
        "xmltex" => 17,
        "latex" | "mllatex" => 16,
        "uplatex-dev" => 15,
        "platex" => 14,
        "pdflatex" | "latex-dev" | "pdflatex-dev" | "xelatex-dev" | "xelatex" | "pdfxmltex" => 11,
        "cont-en" => 10,
        "eplain" => 9,
        "hitex" => 8,
        "pdfcsplain" => 7,
        "etex" | "pdfetex" | "pdftex" | "eptex" => 6,
        "dvilualatex" | "lualatex" | "euptex" | "xetex" => 5,
        "dvilualatex-dev" | "lualatex-dev" => 4,
        "luahbtex" | "luajithbtex" | "luajittex" | "mex" | "mltex" | "mptopdf" | "optex"
        | "ptex" | "texsis" => 3,
        "aleph" | "amstex" | "csplain" | "luacsplain" | "lollipop" | "mf" | "pdfmex"
        | "utf8mex" | "tex" | "uptex" => 2,
        "cslatex" | "pdfcslatex" | "dviluatexluatex" | "mflua" => 1,
        // formati non presenti nel benchmark (nuovi/rari): peso mediano
        // osservato tra quelli misurati, prudente senza essere pessimista
        _ => 5,
    }
}

fn format_weight_ii(name: &str) -> u32 {
    match name {
        "platex" | "platex-dev" => 25,
        "uplatex" => 23,
        "uplatex-dev" => 21,
        "jadetex" | "pdfjadetex" => 17,
        "xmltex" | "pdfxmltex" => 11,
        "eptex" | "euptex" => 6,
        "dvilualatex-dev" | "dvilualatex" | "lualatex" | "lualatex-dev" => 4,
        "luajithbtex" => 3,
        "luahbtex" | "optex" | "tex" | "uptex" | "luajittex" | "ptex" | "lollipop" | "aleph" => 2,
        // tutti gli altri: differenza dal baseline nel rumore di misura
        // (~0.1-1.4s su 3 run), quindi non distinguibile in modo affidabile
        _ => 1,
    }
}
